### ISSUE TITLE
Import of restricted activity doesn't complete cleanly

### ISSUE THREAD

**Issue by ebithell** [moodleuulm/moodle-availability_role#3]
I have been testing a variety of scenarios using restrict by role in both Moodle 3.0.4 and Moodle 3.1.2 (with the appropriate versions of the plugin), and have found an issue with importing.

Steps to reproduce:
1. Restrict an activity/resource to a role (e.g. student)
2. Go to a different course and attempt to import the restricted activity

The import process halts with an error (screenshot attached below). However when you examine the second course, the activity has in fact been imported and restricted correctly.

Would you be able to take a look at this? Thanks!

![import_error](https://cloud.githubusercontent.com/assets/12151818/20183911/e067dd0a-a75e-11e6-8427-8cfe360089b0.png)

**Comment by abias** [comment]
Hi ebithell,

thanks for your report.

There was a problem with restoring restrictions before which was fixed in the 3.1 version of the plugin and was not backported to the 3.0 version because of our support policy.

Could you please verify that you have tried version v3.1-r3 of the plugin from https://moodle.org/plugins/pluginversions.php?plugin=availability_role and report back to me that this problem really does still exist in this version? 

Thanks,
Alex

**Comment by ebithell** [comment]
Hi Alex

I have been working with v3.1-r3 on Moodle 3.1.2 (I looked first at Moodle 3.0, and then moved on to check the most recent versions). Backup & restore works fine now - it is the import function that is still causing an issue in this version.

It would be great if all features did work in Moodle 3.0, but I fully understand your policy about backporting.

Many thanks for your speedy reply,

Erica

**Comment by abias** [comment]
Hi Erica,

we have finally found the time to fix this bug in the latest version. Sorry for the delay.

Thanks,
Alex

**Comment by ebithell** [comment]
Hi Alex

Many thanks for your work on this! I'll be installing it shortly in one of our evaluation Moodle instances - it looks to be a real time-saver for teachers when all users with a given role need the same restriction (saves effort maintaining groups).

Thanks,

Erica
